### ISSUE TITLE
create a game

### ISSUE THREAD

**Issue by clubifaximatic** [drierat/kPAX2_server#6] opened 2016-06-08 06:21 UTC
When create a new game with incorrect parameters the application crash with the following error:

` ` `
POST /game 400 1.776 ms - 14
/Users/bob/git/kPAX2_server/server/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/Users/bob/git/kPAX2_server/server/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/bob/git/kPAX2_server/server/node_modules/express/lib/response.js:163:12)
    at ServerResponse.jsonp (/Users/bob/git/kPAX2_server/server/node_modules/express/lib/response.js:317:15)
    at /Users/bob/git/kPAX2_server/server/routes/game.js:54:10
    at /Users/bob/git/kPAX2_server/server/node_modules/mongodb/lib/collection.js:504:5
    at /Users/bob/git/kPAX2_server/server/node_modules/mongodb/lib/collection.js:666:5
    at handleCallback (/Users/bob/git/kPAX2_server/server/node_modules/mongodb/lib/utils.js:96:12)
    at executeCommands (/Users/bob/git/kPAX2_server/server/node_modules/mongodb/lib/bulk/ordered.js:403:12)
    at resultHandler (/Users/bob/git/kPAX2_server/server/node_modules/mongodb/lib/bulk/ordered.js:430:5)
` ` `

**Comment by mmuntanerm** [comment] 2016-06-09 15:42
Possibly  this issue has been fixed in later reviews ... I am not able to reproduce the issue in my tests. I have been working for fixing some errors of the kind. Hihgly probably, after the last pull request been accepted, things work properly.   ;-)

**Closed as completed** 2016-06-15 06:43 UTC
